/**
 * NFEServices.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package com.mozart.web.wsdl.sosistemas;

public interface NFEServices extends java.rmi.Remote {
    public java.lang.String wbNReciboSefaz(java.lang.String idNota) throws java.rmi.RemoteException;
    public java.lang.String wbRetornoNota(java.lang.String idNota) throws java.rmi.RemoteException;
    public java.lang.String wbGerarXml40(java.lang.String idNota, double frete, double seguro, long idLote) throws java.rmi.RemoteException;
    public java.lang.String wbRequisitarXml(java.lang.String idNota) throws java.rmi.RemoteException;
    public java.lang.String wbCriarNota(java.lang.String token, java.lang.String cpfCnpjEmpresa, java.lang.String cpfCnpjCliente, java.lang.String nomeCliente, java.lang.String cep, java.lang.String foneCliente, long indicadorIdDestinatario, java.lang.String emailCliente, java.util.Calendar dataEmissaoNf, java.lang.String modeloNf, java.lang.String serieNf, java.lang.String numeroNf, long tipoEmissaoNf, java.lang.String codigoNf, java.lang.String natOperacaoNf, java.lang.String indPagNf, java.lang.String tipoNf, java.lang.String idDestNf, java.lang.String tipoImpressao, java.lang.String numeroLote, java.lang.String numeroResidencia, java.lang.String complementoCliente, java.lang.String tfinNfe, java.lang.String indfinal, long indiedest, long tipoPagamento, java.lang.String infcpl, java.lang.String inffonte, java.lang.String infoperador, double vlPago, double vlTroco, java.lang.String tipoFrete, java.lang.String cnpjTransportador, java.lang.String razaoSocialTransportadora, java.lang.String inscEstadualTransportadora, java.lang.String cepTransportadora, java.lang.String logradouroTransportadora, java.lang.String numeroTransportadora, java.lang.String bairroTransportadora, java.lang.String codigoAntt, java.lang.String municipioTransportadora, java.lang.String ufTransportadora, java.lang.String placaVeiculo, java.lang.String qtdTransportado, java.lang.String especie, java.lang.String marca, java.lang.String numeracao, java.lang.String pesoBruto, java.lang.String pesoLiquido, java.lang.String logradouroCliente, java.lang.String bairroCliente, java.util.Calendar dataSaida, java.lang.String ieCliente, java.lang.String nfRef, double vicmsdeson, double vfcpufdest, double vfcp, double vfcpst, double vfcpstret, double vii, double vipidevol, java.lang.String nfat, java.lang.String ndup, java.util.Calendar vencimento, double precoFrete, double valorDesconto) throws java.rmi.RemoteException;
    public java.lang.String wbExportarXml(java.lang.String token, java.lang.String cnpj, java.util.Calendar dataInicial, java.util.Calendar dataFinal) throws java.rmi.RemoteException;
    public java.lang.String wbCancelarNf(java.lang.String token, java.lang.String cnpj, java.lang.String chaveNf, java.lang.String NNf, java.lang.String justificativa) throws java.rmi.RemoteException;
    public java.lang.String wbBuscaIdNota(java.lang.String chaveAcesso) throws java.rmi.RemoteException;
    public java.lang.String wbCartaCorrecao(java.lang.String token, java.lang.String cnpj, java.lang.String chaveNf, java.lang.String NNf, java.lang.String justificativa, java.lang.String orgao, java.lang.String NProtocolo) throws java.rmi.RemoteException;
    public java.lang.String wbGerarXml(java.lang.String idNota, double frete, double seguro, long idLote) throws java.rmi.RemoteException;
    public java.lang.String wbInutilizarNf(java.lang.String token, java.lang.String cnpj, java.lang.String chaveNf, java.lang.String NNf, java.lang.String justificativa, java.lang.String ano, java.lang.String modelo, java.lang.String serie, long numeroInicial, long numeroFinal) throws java.rmi.RemoteException;
    public java.lang.String wbStatusSefaz(java.lang.String token, java.lang.String cpfCnpjEmpresa) throws java.rmi.RemoteException;
    public java.lang.String wbConsultarAutorizacao(java.lang.String NRecibo, java.lang.String cnpj) throws java.rmi.RemoteException;
    public void wbInserirProdutos(java.lang.String idNota, java.lang.String cprod, java.lang.String cean, java.lang.String xprod, java.lang.String ncm, java.lang.String cest, java.lang.String cfop, java.lang.String ucom, java.lang.String qcom, double vuncom, double vprod, java.lang.String ceantrib, java.lang.String utrib, double qtrib, double vuntrib, double vdesc, double voutros, long indtotal, double vtottrib, java.lang.String icmsOrigem, java.lang.String icmsCst, java.lang.String icmsModbc, double icmsRedbc, double icmsVbc, double icmsPicms, double icmsVicms, java.lang.String ipiCenq, java.lang.String ipintCst, java.lang.String pisaliqCst, double pisaliqVbc, double pisaliqPpis, double pisaliqVpis, java.lang.String cofinsaliqCst, double cofinsaliqVbc, double cofinsaliqPcofins, double cofinsaliqVcofins, double icmsPredbc, java.lang.String tipoTributacao, java.lang.String csosn, double vbcstret, double vicmsstret, java.lang.String pisntCst, java.lang.String cofinsntCst, java.lang.String infadprod, java.lang.String ipiCst, double ipiVbc, double ipiPipi, double ipiVipi, double vfcpufdest, double vfcp, double pvcp, double pmvast, double vbcst, double picmsst, double vicmsst) throws java.rmi.RemoteException;
    public java.lang.String wbDanfe(java.lang.String idNota) throws java.rmi.RemoteException;
    public java.lang.String wbRequisitarXmlQrcode(java.lang.String idNota) throws java.rmi.RemoteException;
    public java.lang.String wbEventoCancelamento(java.lang.String token, java.lang.String cnpj, java.lang.String chaveNf, java.lang.String NNf, java.lang.String justificativa, java.lang.String NProtocolo) throws java.rmi.RemoteException;
    public java.lang.String wbNProtocoloSefaz(java.lang.String idNota) throws java.rmi.RemoteException;
    public void wbInserirCombustivel(java.lang.String idNota, java.lang.String cprod, java.lang.String cean, java.lang.String xprod, java.lang.String ncm, java.lang.String cest, java.lang.String cfop, java.lang.String ucom, java.lang.String qcom, double vuncom, double vprod, java.lang.String ceantrib, java.lang.String utrib, double qtrib, double vuntrib, double vdesc, double voutros, long indtotal, double vtottrib, java.lang.String icmsOrigem, java.lang.String icmsCst, java.lang.String icmsModbc, double icmsRedbc, double icmsVbc, double icmsPicms, double icmsVicms, java.lang.String ipiCenq, java.lang.String ipintCst, java.lang.String pisaliqCst, double pisaliqVbc, double pisaliqPpis, double pisaliqVpis, java.lang.String cofinsaliqCst, double cofinsaliqVbc, double cofinsaliqPcofins, double cofinsaliqVcofins, double icmsPredbc, java.lang.String tipoTributacao, java.lang.String csosn, double vbcstret, double vicmsstret, java.lang.String pisntCst, java.lang.String cofinsntCst, java.lang.String infadprod, java.lang.String cprodAnp, double qtemp, java.lang.String ufCons, double qbcprod, double valiqprod, double vcide, java.lang.String codif, java.lang.String ipiCst, double ipiVbc, double ipiPipi, double ipiVipi) throws java.rmi.RemoteException;
}
